-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.person
(
    id serial NOT NULL,
    firts_name character(50) NOT NULL,
    last_name character(50) NOT NULL,
    email text NOT NULL,
    password text NOT NULL,
    salt text NOT NULL,
    image text NOT NULL,
    description text,
    create_at timestamp without time zone,
    update_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public." tournament"
(
    id serial NOT NULL,
    name text NOT NULL,
    reward real NOT NULL,
    start_at date NOT NULL,
    image text NOT NULL,
    description text,
    create_at timestamp without time zone,
    update_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.team
(
    id serial NOT NULL,
    person_id bigint NOT NULL,
    name character(25) NOT NULL,
    image text NOT NULL,
    description text,
    create_at timestamp without time zone,
    "update-at" timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.team_members
(
    id serial NOT NULL,
    team_id bigint NOT NULL,
    person_id bigint NOT NULL,
    description text,
    create_at timestamp without time zone,
    update_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.participating_teams
(
    id serial NOT NULL,
    tournament_id bigint NOT NULL,
    team_id bigint NOT NULL,
    description text,
    create_at timestamp without time zone,
    update_at timestamp without time zone,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.team_members
    ADD FOREIGN KEY (team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.team_members
    ADD FOREIGN KEY (person_id)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.participating_teams
    ADD FOREIGN KEY (tournament_id)
    REFERENCES public." tournament" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.participating_teams
    ADD FOREIGN KEY (team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;